export const timezones = [
  { name: 'UTC', offset: '+00:00' },
  // Africa
  { name: 'Africa/Cairo', offset: '+02:00' },
  { name: 'Africa/Johannesburg', offset: '+02:00' },
  { name: 'Africa/Lagos', offset: '+01:00' },
  { name: 'Africa/Nairobi', offset: '+03:00' },
  // America
  { name: 'America/Anchorage', offset: '-09:00' },
  { name: 'America/Argentina/Buenos_Aires', offset: '-03:00' },
  { name: 'America/Bogota', offset: '-05:00' },
  { name: 'America/Chicago', offset: '-06:00' },
  { name: 'America/Denver', offset: '-07:00' },
  { name: 'America/Halifax', offset: '-04:00' },
  { name: 'America/Los_Angeles', offset: '-08:00' },
  { name: 'America/Mexico_City', offset: '-06:00' },
  { name: 'America/New_York', offset: '-05:00' },
  { name: 'America/Phoenix', offset: '-07:00' },
  { name: 'America/Santiago', offset: '-04:00' },
  { name: 'America/Sao_Paulo', offset: '-03:00' },
  { name: 'America/Toronto', offset: '-05:00' },
  { name: 'America/Vancouver', offset: '-08:00' },
  // Asia
  { name: 'Asia/Bangkok', offset: '+07:00' },
  { name: 'Asia/Dubai', offset: '+04:00' },
  { name: 'Asia/Hong_Kong', offset: '+08:00' },
  { name: 'Asia/Jakarta', offset: '+07:00' },
  { name: 'Asia/Jerusalem', offset: '+02:00' },
  { name: 'Asia/Kolkata', offset: '+05:30' },
  { name: 'Asia/Kuwait', offset: '+03:00' },
  { name: 'Asia/Manila', offset: '+08:00' },
  { name: 'Asia/Seoul', offset: '+09:00' },
  { name: 'Asia/Shanghai', offset: '+08:00' },
  { name: 'Asia/Singapore', offset: '+08:00' },
  { name: 'Asia/Taipei', offset: '+08:00' },
  { name: 'Asia/Tokyo', offset: '+09:00' },
  // Australia
  { name: 'Australia/Adelaide', offset: '+09:30' },
  { name: 'Australia/Brisbane', offset: '+10:00' },
  { name: 'Australia/Darwin', offset: '+09:30' },
  { name: 'Australia/Melbourne', offset: '+10:00' },
  { name: 'Australia/Perth', offset: '+08:00' },
  { name: 'Australia/Sydney', offset: '+10:00' },
  // Europe
  { name: 'Europe/Amsterdam', offset: '+01:00' },
  { name: 'Europe/Athens', offset: '+02:00' },
  { name: 'Europe/Berlin', offset: '+01:00' },
  { name: 'Europe/Brussels', offset: '+01:00' },
  { name: 'Europe/Budapest', offset: '+01:00' },
  { name: 'Europe/Copenhagen', offset: '+01:00' },
  { name: 'Europe/Dublin', offset: '+00:00' },
  { name: 'Europe/Helsinki', offset: '+02:00' },
  { name: 'Europe/Istanbul', offset: '+03:00' },
  { name: 'Europe/Lisbon', offset: '+00:00' },
  { name: 'Europe/London', offset: '+00:00' },
  { name: 'Europe/Madrid', offset: '+01:00' },
  { name: 'Europe/Moscow', offset: '+03:00' },
  { name: 'Europe/Oslo', offset: '+01:00' },
  { name: 'Europe/Paris', offset: '+01:00' },
  { name: 'Europe/Prague', offset: '+01:00' },
  { name: 'Europe/Rome', offset: '+01:00' },
  { name: 'Europe/Stockholm', offset: '+01:00' },
  { name: 'Europe/Vienna', offset: '+01:00' },
  { name: 'Europe/Warsaw', offset: '+01:00' },
  { name: 'Europe/Zurich', offset: '+01:00' },
  // Pacific
  { name: 'Pacific/Auckland', offset: '+12:00' },
  { name: 'Pacific/Fiji', offset: '+12:00' },
  { name: 'Pacific/Honolulu', offset: '-10:00' },
  { name: 'Pacific/Samoa', offset: '+13:00' }
];